version: "3.8"
services:
  spark:
    build: .
    volumes:
      - ../../:/workspace
      - ./data:/data
    working_dir: /workspace
    command: ["sleep", "infinity"]
    environment:
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
      - SPARK_MEMORY_FRACTION=0.8
      - SPARK_MEMORY_STORAGE_FRACTION=0.3
